<?php

namespace App\Entity\Settings;

class Country
{
    public const DEFAULT_CODE = 'DEFAULT';
    public const COUNTRIES    = [
        "US" => "United States",
        "RU" => "Russia",
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "BQ" => "British Antarctic Territory",
        "IO" => "British Indian Ocean Territory",
        "VG" => "British Virgin Islands",
        "BN" => "Brunei",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CT" => "Canton and Enderbury Islands",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos [Keeling] Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo - Brazzaville",
        "CD" => "Congo - Kinshasa",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "CI" => "Côte d’Ivoire",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "NQ" => "Dronning Maud Land",
        "DD" => "East Germany",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "FQ" => "French Southern and Antarctic Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HK" => "Hong Kong SAR China",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey",
        "JT" => "Johnston Island",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Laos",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macau SAR China",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "FX" => "Metropolitan France",
        "MX" => "Mexico",
        "FM" => "Micronesia",
        "MI" => "Midway Islands",
        "MD" => "Moldova",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar [Burma]",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "AN" => "Netherlands Antilles",
        "NT" => "Neutral Zone",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "KP" => "North Korea",
        "VD" => "North Vietnam",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PC" => "Pacific Islands Trust Territory",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territories",
        "PA" => "Panama",
        "PZ" => "Panama Canal Zone",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "YD" => "People's Democratic Republic of Yemen",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn Islands",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RO" => "Romania",
        "RW" => "Rwanda",
        "RE" => "Réunion",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "CS" => "Serbia and Montenegro",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia and the South Sandwich Islands",
        "KR" => "South Korea",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syria",
        "ST" => "São Tomé and Príncipe",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UM" => "U.S. Minor Outlying Islands",
        "PU" => "U.S. Miscellaneous Pacific Islands",
        "VI" => "U.S. Virgin Islands",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VA" => "Vatican City",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "WK" => "Wake Island",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
        "AX" => "Åland Islands",
        "ZZ" => "Unknown or Invalid Region",
    ];
    public const CODES        = [
        "AF",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BA",
        "BW",
        "BV",
        "BR",
        "BQ",
        "IO",
        "VG",
        "BN",
        "BG",
        "BF",
        "BI",
        "KH",
        "CM",
        "CA",
        "CT",
        "CV",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "HR",
        "CU",
        "CY",
        "CZ",
        "CI",
        "DK",
        "DJ",
        "DM",
        "DO",
        "NQ",
        "DD",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "FQ",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JT",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MK",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "FX",
        "MX",
        "FM",
        "MI",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "AN",
        "NT",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "VD",
        "MP",
        "NO",
        "OM",
        "PC",
        "PK",
        "PW",
        "PS",
        "PA",
        "PZ",
        "PG",
        "PY",
        "YD",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RO",
        "RU",
        "RW",
        "RE",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "SA",
        "SN",
        "RS",
        "CS",
        "SC",
        "SL",
        "SG",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SZ",
        "SE",
        "CH",
        "SY",
        "ST",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UM",
        "PU",
        "VI",
        "UG",
        "UA",
        "SU",
        "AE",
        "GB",
        "US",
        "ZZ",
        "UY",
        "UZ",
        "VU",
        "VA",
        "VE",
        "VN",
        "WK",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
        "AX",
    ];

    public const FLAGS = [
        "DEFAULT" => "countries-flags/default.svg",

        "AD" => "countries-flags/AD.svg",
        "AE" => "countries-flags/AE.svg",
        "AF" => "countries-flags/AF.svg",
        "AG" => "countries-flags/AG.svg",
        "AI" => "countries-flags/AI.svg",
        "AL" => "countries-flags/AL.svg",
        "AM" => "countries-flags/AM.svg",
        "AN" => "countries-flags/AN.svg",
        "AO" => "countries-flags/AO.svg",
        "AQ" => "countries-flags/AQ.svg",
        "AR" => "countries-flags/AR.svg",
        "AS" => "countries-flags/AS.svg",
        "AT" => "countries-flags/AT.svg",
        "AU" => "countries-flags/AU.svg",
        "AW" => "countries-flags/AW.svg",
        "AX" => "countries-flags/AX.svg",
        "AZ" => "countries-flags/AZ.svg",
        "BA" => "countries-flags/BA.svg",
        "BB" => "countries-flags/BB.svg",
        "BD" => "countries-flags/BD.svg",
        "BE" => "countries-flags/BE.svg",
        "BF" => "countries-flags/BF.svg",
        "BG" => "countries-flags/BG.svg",
        "BH" => "countries-flags/BH.svg",
        "BI" => "countries-flags/BI.svg",
        "BJ" => "countries-flags/BJ.svg",
        "BL" => "countries-flags/BL.svg",
        "BM" => "countries-flags/BM.svg",
        "BN" => "countries-flags/BN.svg",
        "BO" => "countries-flags/BO.svg",
        "BQ" => "countries-flags/BQ.svg",
        "BR" => "countries-flags/BR.svg",
        "BS" => "countries-flags/BS.svg",
        "BT" => "countries-flags/BT.svg",
        "BV" => "countries-flags/BV.svg",
        "BW" => "countries-flags/BW.svg",
        "BY" => "countries-flags/BY.svg",
        "BZ" => "countries-flags/BZ.svg",
        "CA" => "countries-flags/CA.svg",
        "CC" => "countries-flags/CC.svg",
        "CD" => "countries-flags/CD.svg",
        "CF" => "countries-flags/CF.svg",
        "CG" => "countries-flags/CG.svg",
        "CH" => "countries-flags/CH.svg",
        "CI" => "countries-flags/CI.svg",
        "CK" => "countries-flags/CK.svg",
        "CL" => "countries-flags/CL.svg",
        "CM" => "countries-flags/CM.svg",
        "CN" => "countries-flags/CN.svg",
        "CO" => "countries-flags/CO.svg",
        "CR" => "countries-flags/CR.svg",
        "CS" => "countries-flags/CS.svg",
        "CT" => "countries-flags/CT.svg",
        "CU" => "countries-flags/CU.svg",
        "CV" => "countries-flags/CV.svg",
        "CX" => "countries-flags/CX.svg",
        "CY" => "countries-flags/CY.svg",
        "CZ" => "countries-flags/CZ.svg",
        "DD" => "countries-flags/DD.svg",
        "DE" => "countries-flags/DE.svg",
        "DJ" => "countries-flags/DJ.svg",
        "DK" => "countries-flags/DK.svg",
        "DM" => "countries-flags/DM.svg",
        "DO" => "countries-flags/DO.svg",
        "DZ" => "countries-flags/DZ.svg",
        "EC" => "countries-flags/EC.svg",
        "EE" => "countries-flags/EE.svg",
        "EG" => "countries-flags/EG.svg",
        "EH" => "countries-flags/EH.svg",
        "ER" => "countries-flags/ER.svg",
        "ES" => "countries-flags/ES.svg",
        "ET" => "countries-flags/ET.svg",
        "FI" => "countries-flags/FI.svg",
        "FJ" => "countries-flags/FJ.svg",
        "FK" => "countries-flags/FK.svg",
        "FM" => "countries-flags/FM.svg",
        "FO" => "countries-flags/FO.svg",
        "FQ" => "countries-flags/FQ.svg",
        "FR" => "countries-flags/FR.svg",
        "FX" => "countries-flags/FX.svg",
        "GA" => "countries-flags/GA.svg",
        "GB" => "countries-flags/GB.svg",
        "GD" => "countries-flags/GD.svg",
        "GE" => "countries-flags/GE.svg",
        "GF" => "countries-flags/GF.svg",
        "GG" => "countries-flags/GG.svg",
        "GH" => "countries-flags/GH.svg",
        "GI" => "countries-flags/GI.svg",
        "GL" => "countries-flags/GL.svg",
        "GM" => "countries-flags/GM.svg",
        "GN" => "countries-flags/GN.svg",
        "GP" => "countries-flags/GP.svg",
        "GQ" => "countries-flags/GQ.svg",
        "GR" => "countries-flags/GR.svg",
        "GS" => "countries-flags/GS.svg",
        "GT" => "countries-flags/GT.svg",
        "GU" => "countries-flags/GU.svg",
        "GW" => "countries-flags/GW.svg",
        "GY" => "countries-flags/GY.svg",
        "HK" => "countries-flags/HK.svg",
        "HM" => "countries-flags/HM.svg",
        "HN" => "countries-flags/HN.svg",
        "HR" => "countries-flags/HR.svg",
        "HT" => "countries-flags/HT.svg",
        "HU" => "countries-flags/HU.svg",
        "ID" => "countries-flags/ID.svg",
        "IE" => "countries-flags/IE.svg",
        "IL" => "countries-flags/IL.svg",
        "IM" => "countries-flags/IM.svg",
        "IN" => "countries-flags/IN.svg",
        "IO" => "countries-flags/IO.svg",
        "IQ" => "countries-flags/IQ.svg",
        "IR" => "countries-flags/IR.svg",
        "IS" => "countries-flags/IS.svg",
        "IT" => "countries-flags/IT.svg",
        "JE" => "countries-flags/JE.svg",
        "JM" => "countries-flags/JM.svg",
        "JO" => "countries-flags/JO.svg",
        "JP" => "countries-flags/JP.svg",
        "JT" => "countries-flags/JT.svg",
        "KE" => "countries-flags/KE.svg",
        "KG" => "countries-flags/KG.svg",
        "KH" => "countries-flags/KH.svg",
        "KI" => "countries-flags/KI.svg",
        "KM" => "countries-flags/KM.svg",
        "KN" => "countries-flags/KN.svg",
        "KP" => "countries-flags/KP.svg",
        "KR" => "countries-flags/KR.svg",
        "KW" => "countries-flags/KW.svg",
        "KY" => "countries-flags/KY.svg",
        "KZ" => "countries-flags/KZ.svg",
        "LA" => "countries-flags/LA.svg",
        "LB" => "countries-flags/LB.svg",
        "LC" => "countries-flags/LC.svg",
        "LI" => "countries-flags/LI.svg",
        "LK" => "countries-flags/LK.svg",
        "LR" => "countries-flags/LR.svg",
        "LS" => "countries-flags/LS.svg",
        "LT" => "countries-flags/LT.svg",
        "LU" => "countries-flags/LU.svg",
        "LV" => "countries-flags/LV.svg",
        "LY" => "countries-flags/LY.svg",
        "MA" => "countries-flags/MA.svg",
        "MC" => "countries-flags/MC.svg",
        "MD" => "countries-flags/MD.svg",
        "ME" => "countries-flags/ME.svg",
        "MF" => "countries-flags/MF.svg",
        "MG" => "countries-flags/MG.svg",
        "MH" => "countries-flags/MH.svg",
        "MI" => "countries-flags/MI.svg",
        "MK" => "countries-flags/MK.svg",
        "ML" => "countries-flags/ML.svg",
        "MM" => "countries-flags/MM.svg",
        "MN" => "countries-flags/MN.svg",
        "MO" => "countries-flags/MO.svg",
        "MP" => "countries-flags/MP.svg",
        "MQ" => "countries-flags/MQ.svg",
        "MR" => "countries-flags/MR.svg",
        "MS" => "countries-flags/MS.svg",
        "MT" => "countries-flags/MT.svg",
        "MU" => "countries-flags/MU.svg",
        "MV" => "countries-flags/MV.svg",
        "MW" => "countries-flags/MW.svg",
        "MX" => "countries-flags/MX.svg",
        "MY" => "countries-flags/MY.svg",
        "MZ" => "countries-flags/MZ.svg",
        "NA" => "countries-flags/NA.svg",
        "NC" => "countries-flags/NC.svg",
        "NE" => "countries-flags/NE.svg",
        "NF" => "countries-flags/NF.svg",
        "NG" => "countries-flags/NG.svg",
        "NI" => "countries-flags/NI.svg",
        "NL" => "countries-flags/NL.svg",
        "NO" => "countries-flags/NO.svg",
        "NP" => "countries-flags/NP.svg",
        "NQ" => "countries-flags/NQ.svg",
        "NR" => "countries-flags/NR.svg",
        "NT" => "countries-flags/NT.svg",
        "NU" => "countries-flags/NU.svg",
        "NZ" => "countries-flags/NZ.svg",
        "OM" => "countries-flags/OM.svg",
        "PA" => "countries-flags/PA.svg",
        "PC" => "countries-flags/PC.svg",
        "PE" => "countries-flags/PE.svg",
        "PF" => "countries-flags/PF.svg",
        "PG" => "countries-flags/PG.svg",
        "PH" => "countries-flags/PH.svg",
        "PK" => "countries-flags/PK.svg",
        "PL" => "countries-flags/PL.svg",
        "PM" => "countries-flags/PM.svg",
        "PN" => "countries-flags/PN.svg",
        "PR" => "countries-flags/PR.svg",
        "PS" => "countries-flags/PS.svg",
        "PT" => "countries-flags/PT.svg",
        "PU" => "countries-flags/PU.svg",
        "PW" => "countries-flags/PW.svg",
        "PY" => "countries-flags/PY.svg",
        "PZ" => "countries-flags/PZ.svg",
        "QA" => "countries-flags/QA.svg",
        "RE" => "countries-flags/RE.svg",
        "RO" => "countries-flags/RO.svg",
        "RS" => "countries-flags/RS.svg",
        "RU" => "countries-flags/RU.svg",
        "RW" => "countries-flags/RW.svg",
        "SA" => "countries-flags/SA.svg",
        "SB" => "countries-flags/SB.svg",
        "SC" => "countries-flags/SC.svg",
        "SD" => "countries-flags/SD.svg",
        "SE" => "countries-flags/SE.svg",
        "SG" => "countries-flags/SG.svg",
        "SH" => "countries-flags/SH.svg",
        "SI" => "countries-flags/SI.svg",
        "SJ" => "countries-flags/SJ.svg",
        "SK" => "countries-flags/SK.svg",
        "SL" => "countries-flags/SL.svg",
        "SM" => "countries-flags/SM.svg",
        "SN" => "countries-flags/SN.svg",
        "SO" => "countries-flags/SO.svg",
        "SR" => "countries-flags/SR.svg",
        "ST" => "countries-flags/ST.svg",
        "SV" => "countries-flags/SV.svg",
        "SY" => "countries-flags/SY.svg",
        "SZ" => "countries-flags/SZ.svg",
        "TC" => "countries-flags/TC.svg",
        "TD" => "countries-flags/TD.svg",
        "TF" => "countries-flags/TF.svg",
        "TG" => "countries-flags/TG.svg",
        "TH" => "countries-flags/TH.svg",
        "TJ" => "countries-flags/TJ.svg",
        "TK" => "countries-flags/TK.svg",
        "TL" => "countries-flags/TL.svg",
        "TM" => "countries-flags/TM.svg",
        "TN" => "countries-flags/TN.svg",
        "TO" => "countries-flags/TO.svg",
        "TR" => "countries-flags/TR.svg",
        "TT" => "countries-flags/TT.svg",
        "TV" => "countries-flags/TV.svg",
        "TW" => "countries-flags/TW.svg",
        "TZ" => "countries-flags/TZ.svg",
        "UA" => "countries-flags/UA.svg",
        "UG" => "countries-flags/UG.svg",
        "UM" => "countries-flags/UM.svg",
        "US" => "countries-flags/US.svg",
        "UY" => "countries-flags/UY.svg",
        "UZ" => "countries-flags/UZ.svg",
        "VA" => "countries-flags/VA.svg",
        "VC" => "countries-flags/VC.svg",
        "VD" => "countries-flags/VD.svg",
        "VE" => "countries-flags/VE.svg",
        "VG" => "countries-flags/VG.svg",
        "VI" => "countries-flags/VI.svg",
        "VN" => "countries-flags/VN.svg",
        "VU" => "countries-flags/VU.svg",
        "WF" => "countries-flags/WF.svg",
        "WK" => "countries-flags/WK.svg",
        "WS" => "countries-flags/WS.svg",
        "YD" => "countries-flags/YD.svg",
        "YE" => "countries-flags/YE.svg",
        "YT" => "countries-flags/YT.svg",
        "ZA" => "countries-flags/ZA.svg",
        "ZM" => "countries-flags/ZM.svg",
        "ZW" => "countries-flags/ZW.svg",
        "ZZ" => "countries-flags/default.svg",
    ];

    public const FLAGS_EXCLUDE_SHOW = [
        "ZZ",
    ];
}
