api_platform:
    title: API Purple Box Online
    version: 1.0.0
    formats:
        json:
            mime_types:
                - application/json
                - application/merge-patch+json
                - application/ld+json
                - text/event-stream
                - application/x-www-form-urlencoded
        jsonld:   ['application/json']
        multipart: ['multipart/form-data']
        form: ['application/x-www-form-urlencoded']
    docs_formats:
        json: ['application/merge-patch+json']
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    patch_formats:
        json: ['application/merge-patch+json']
        multipart: ['multipart/form-data']
    mapping:
        paths: [
                   '%kernel.project_dir%/src/ApiDTO',
                   '%kernel.project_dir%/src/Entity',
                   '%kernel.project_dir%/src/Controller',
                   '%kernel.project_dir%/src/User/Controller',
        ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
